# Logo Url
# Please enter the absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo: http://geosmart.github.io/css/images/logo.png

# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  About: /about/index.html

# Article list grouped by year
groupByYear: false

# Content
fancybox: true

# Thumbnail
thumbnail: false

# Scroll Loading
scrollLoading: true

#Sidebar(right/left)
sidebar: left

social_links:
  github: https://github.com/geosmart
  weibo: http://weibo.com/geosmart
  google_plus:
  rss: atom.xml

widgets:
- recent_posts
- category
- archive
#- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io
  ltsoft: http://ltsoft.github.io

# Miscellaneous #社交网络和统计连接地址
baidu_analytics: //hm.baidu.com/hm.js?221699150bf25edfe6338d0a9f205159

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false




# Miscellaneous
#google_analytics:
favicon: /favicon.png
fb_admins:
fb_app_id:
